/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-17-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class VsController {
    public VsController() {

    }
    @AuraEnabled //In LWC public Void Not USed So incase We use @AuraEnabled Annotation(Static Method)
    //Also (Cachable=true)
    public static string methodName(){
         String str='';
         return '';
    }

}